### PR TITLE
SoD engraving, keybinds

### PR DESCRIPTION
**Pull request by Road-block**

### CODE REVIEW

**Comment by Rottenbeer** [comment]
thanks for the PR.
did you test this on wow classic, sod, wotlk(or all the other variants)
my subscription expired, so I can't test it.

**Comment by Road-block** [comment]
SoD and wotlk, no other variants.

**Comment by Road-block** [comment]
> Alternatively deleting the entire `SaveBindings` call as it's redundant since they are loaded at login.

I don't believe that's true for non-static bindings (ie not created through a bindings.xml file)
That's the whole reason the call was put there originally (not my addon / code but that's my guess).

**Comment by Rottenbeer** [comment]
Thanks again for the PR, it's released on curseforge as 3.77.
@RealityWinner Can you open a PR, we'll check if @Road-block changes fixes the issue and i'll look at yours if it doesn't

**Pull request merged**
