### PR TITLE
Remove in combat / dead item swapping

### PR DESCRIPTION
**Pull request by Phatcat**
Fix in combat (and dead) item swapping which is a restricted action in Classic

### CODE REVIEW

**Comment by Phatcat** [comment]
I already tested this locally and it works as expected, swapping no longer happens once combat has been entered. I do not know if it will place the items in a 'queue' for swapping when you leave combat or if it just outright drops it, I didn't really look into the codebase or how it works together.

**Comment by Phatcat** [comment]
I made a comment on curseforge when I opened this PR but, well, ehh... it seems to be gone now. Maybe it never posted it in the first place.

**Comment by Phatcat** [comment]
Okay, so I 'broke' the queue functionality while in combat with my first fix so I took a look at it again and got the combat queue working again.

If you are interested I can take a look at if I can find a way to make weapon swapping work in combat (if this is allowed through addons in classic at all, I know they're trying to avoid the shitshow that was the 1.12 api that allowed for almost entirely automated playing) , but in all honesty I would much rather want to take a stab at trying to get Outfitter up and running again, both because it existed back in 2006 so for nostalgia, but also because it is so much more intuitive, but I was tired of this addon not working and thought some people might appreciate getting this up and running again. I actually only took a look at this because someone was complaining combat swapping was broken and you said you couldn't quite find the issue.

**Comment by Rottenbeer** [comment]
Hi!
Thenks for sending a PR, I'll have a look this evening. 

I know how to fix the Lua error that appears when switching sets in combat, but I don't know how to make weapon switching in combat actually work. Seems like blizzard disabled the possibility for addons to do this. If you can find I way how to enable weapon switching in combat, I would highly appreciate it. 

Fixing Outfitter is another story, I had a look at the code before I ported ItemRack but it seemed to be way more complex, so I decided against it.

**Comment by Rottenbeer** [comment]
Hi!
Thenks for sending a PR, I'll have a look this evening. 

I know how to fix the Lua error that appears when switching sets in combat, but I don't know how to make weapon switching in combat actually work. Seems like blizzard disabled the possibility for addons to do this. If you can find I way how to enable weapon switching in combat, I would highly appreciate it. 

Fixing Outfitter is another story, I had a look at the code before I ported ItemRack but it seemed to be way more complex, so I decided against it.

**Comment by Phatcat** [comment]
. . .

This fix is not to 'remove the lua errors', this fix is to fix the broken combat swapping. Disabling combat swapping and queing the items in the addon for now seems better than to leave it broken forcing the player to relog, if it's a protected function then it's never going to be possible anyway.

**Comment by Phatcat** [comment]
From the error message in https://github.com/Rottenbeer/ItemRack/issues/26

"Message: Note: AddOn ItemRack attempted to call a protected function (PickupInventoryItem()) during combat lockdown."

If PickupInventoryItem() is protected, then the addon will never be able to combatswap, since it won't ever be able to pick up anything from the inventory. There is no 'fixing' this as it's clearly intended by Blizzard that this is protected (at least for now, and I don't see why they'd change that).

**Comment by Phatcat** [comment]
More is written about it here; https://wowwiki.fandom.com/wiki/Secure_Execution_and_Tainting - addons are simply not allowed to use protected functions as addons are not considered 'secure code' - It can never be and never will be considered 'secure code'.

I hate to be the bearer of bad news, but... There's no way for an addon not to be 'insecure code' and there's no way for insecure code to use protected functions, and in Classic, both PickupInventoryItem() and PickupContainerItem() are both protected functions (it is even evident by the issues posted here, on this very repo, where Blizzard reports that the functions are Protected, to assuming they are 'not' protected is a bit silly to me), meaning addons will never have access to it with the current classic api. 

Looks like it's macros or nothing for  in-combat weapon swapping in classic *shrugs*

**Comment by Rottenbeer** [comment]
Tested and it works very good. Thanks!

**Pull request merged**
