### PR TITLE
Use LibDBIcon-1.0 and some small changes

### LINKED ISSUE #134: Minimap button does not recognize resized minimap
If the minimap is resized (for exmple with elvui), the button does not follow the map outline when dragged, rather goes through the middle of it if minimap is made larger.

image

### PR DESCRIPTION
**Pull request by mrbuds**
https://github.com/Rottenbeer/ItemRack/commit/66041e577bafbd804d69893293c69ddfa1983f83 makes github repo usable without packaging, you only need to copy libs from package to your local copy once

https://github.com/Rottenbeer/ItemRack/commit/03b3a32118784fb438fb87023d9438385b08440f fixes some variables

https://github.com/Rottenbeer/ItemRack/commit/b5c0371708f760f9efd9ec0e5f31f0aff8b7650a keep dependencies updates

https://github.com/Rottenbeer/ItemRack/commit/412cac71f8e240521cd0086b88b3723fbb79788a replace minimap's icon code to use LibDBIcon-1.0 and LibDataBroker-1.1, fixes #134
This make the addon integrate better with other addons and give users more choice on how to show this icon.
I tried my best to not lose any function, but i'v removed the ShineFadeIn animation

### CODE REVIEW

**Comment by Rottenbeer** [comment]
Hi

Thanks for the pull request and your efforts!
I tried to build a release
`» ./release.sh -d -g bcc -n "{package-name}-{project-version}" -p 340903
Packaging ItemRack
Current version: 3.63-4-g412cac7
Previous version: 3.63
Build type: non-retail version-bcc alpha non-debug
Game version: 2.5.1

CurseForge ID: 340903
GitHub: Rottenbeer/ItemRack

Checkout directory: /mnt/d/git/ItemRack
Release directory: /mnt/d/git/ItemRack/.release

Copying files into .release/ItemRack:
  Copying: Changelog.txt
  Copying: ItemRack/Brackets.tga (unchanged)
  Copying: ItemRack/ItemRack.lua
  Copying: ItemRack/ItemRack.toc
  Copying: ItemRack/ItemRack.xml
  Copying: ItemRack/ItemRackButtons.blp (unchanged)
  Copying: ItemRack/ItemRackButtons.lua
  Copying: ItemRack/ItemRackButtons.xml
  Copying: ItemRack/ItemRackEquip.lua
  Copying: ItemRack/ItemRackEvents.lua
  Copying: ItemRack/ItemRackGear.blp (unchanged)
  Copying: ItemRack/ItemRackIcon.blp (unchanged)
  Copying: ItemRack/ItemRackQueue.lua
  Copying: ItemRack/Libs/Libs.xml
  Copying: ItemRack/readme.txt
  Ignoring: ItemRack.zip
  Copying: ItemRackOptions/ItemRackOptions.lua
  Copying: ItemRackOptions/ItemRackOptions.toc
  Copying: ItemRackOptions/ItemRackOptions.xml
  Copying: ItemRackOptions/ItemRackOptTabs.tga (unchanged)
  Copying: ItemRackOptions/ItemRackScriptIcon.tga (unchanged)
  Copying: ItemRackOptions/Libs/Libs.xml
  Ignoring: README.md

Fetching external: ItemRack/Libs/LibStub
Fetching external: ItemRack/Libs/LibDataBroker-1.1
Fetching external: ItemRack/Libs/LibDBIcon-1.0
Fetching external: ItemRackOptions/Libs/LibStub

Waiting for externals to finish...

Fetching latest version of external https://github.com/tekkub/libdatabroker-1-1
Checked out v1.1.4-0-g1a63ede
Copying files into .release/ItemRack/ItemRack/Libs/LibDataBroker-1.1:
  Copying: LibDataBroker-1.1.lua
  Copying: README.textile (unchanged)

Fetching latest version of external https://repos.curseforge.com/wow/libdbicon-1-0/trunk/LibDBIcon-1.0
Checked out r84
Copying files into .release/ItemRack/ItemRack/Libs/LibDBIcon-1.0:
  Copying: lib.xml
  Copying: LibDBIcon-1.0.lua

Fetching latest version of external https://repos.curseforge.com/wow/libstub/trunk
Checked out r109
Copying files into .release/ItemRack/ItemRack/Libs/LibStub:
  Copying: LibStub.lua
  Copying: LibStub.toc
  Copying: tests/test.lua
  Copying: tests/test2.lua
  Copying: tests/test3.lua
  Copying: tests/test4.lua

Fetching latest version of external https://repos.curseforge.com/wow/libstub/trunk
Checked out r109
Copying files into .release/ItemRack/ItemRackOptions/Libs/LibStub:
  Copying: LibStub.lua
  Copying: LibStub.toc
  Copying: tests/test.lua
  Copying: tests/test2.lua
  Copying: tests/test3.lua
  Copying: tests/test4.lua

Using manual changelog at Changelog.txt
__ New in 3.63 - By Rottenbeer __
* Version bump for github releases

__ New in 3.62 - By Rottenbeer __
* Fix luacheck errors

__ New in 3.61 - By Rottenbeer __
...

Moving ItemRack/ItemRack to ItemRack
Moving ItemRack/ItemRackOptions to ItemRackOptions

Creating archive: ItemRack-3.63-4-g412cac7.zip
  adding: ItemRack/ (stored 0%)
  adding: ItemRack/Brackets.tga (deflated 99%)
  adding: ItemRack/Changelog.txt (deflated 62%)
  adding: ItemRack/ItemRack.lua (deflated 74%)
  adding: ItemRack/ItemRack.toc (deflated 43%)
  adding: ItemRack/ItemRack.xml (deflated 74%)
  adding: ItemRack/ItemRackButtons.blp (deflated 85%)
  adding: ItemRack/ItemRackButtons.lua (deflated 78%)
  adding: ItemRack/ItemRackButtons.xml (deflated 86%)
  adding: ItemRack/ItemRackEquip.lua (deflated 70%)
  adding: ItemRack/ItemRackEvents.lua (deflated 73%)
  adding: ItemRack/ItemRackGear.blp (deflated 78%)
  adding: ItemRack/ItemRackIcon.blp (deflated 41%)
  adding: ItemRack/ItemRackQueue.lua (deflated 64%)
  adding: ItemRack/Libs/ (stored 0%)
  adding: ItemRack/Libs/LibDataBroker-1.1/ (stored 0%)
  adding: ItemRack/Libs/LibDataBroker-1.1/LibDataBroker-1.1.lua (deflated 74%)
  adding: ItemRack/Libs/LibDataBroker-1.1/README.textile (deflated 49%)
  adding: ItemRack/Libs/LibDBIcon-1.0/ (stored 0%)
  adding: ItemRack/Libs/LibDBIcon-1.0/lib.xml (deflated 29%)
  adding: ItemRack/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua (deflated 75%)
  adding: ItemRack/Libs/Libs.xml (deflated 44%)
  adding: ItemRack/Libs/LibStub/ (stored 0%)
  adding: ItemRack/Libs/LibStub/LibStub.lua (deflated 56%)
  adding: ItemRack/Libs/LibStub/LibStub.toc (deflated 26%)
  adding: ItemRack/Libs/LibStub/tests/ (stored 0%)
  adding: ItemRack/Libs/LibStub/tests/test.lua (deflated 71%)
  adding: ItemRack/Libs/LibStub/tests/test2.lua (deflated 58%)
  adding: ItemRack/Libs/LibStub/tests/test3.lua (deflated 52%)
  adding: ItemRack/Libs/LibStub/tests/test4.lua (deflated 66%)
  adding: ItemRack/readme.txt (deflated 58%)
  adding: ItemRackOptions/ (stored 0%)
  adding: ItemRackOptions/ItemRackOptions.lua (deflated 79%)
  adding: ItemRackOptions/ItemRackOptions.toc (deflated 31%)
  adding: ItemRackOptions/ItemRackOptions.xml (deflated 90%)
  adding: ItemRackOptions/ItemRackOptTabs.tga (deflated 90%)
  adding: ItemRackOptions/ItemRackScriptIcon.tga (deflated 48%)
  adding: ItemRackOptions/Libs/ (stored 0%)
  adding: ItemRackOptions/Libs/Libs.xml (deflated 29%)
  adding: ItemRackOptions/Libs/LibStub/ (stored 0%)
  adding: ItemRackOptions/Libs/LibStub/LibStub.lua (deflated 56%)
  adding: ItemRackOptions/Libs/LibStub/LibStub.toc (deflated 26%)
  adding: ItemRackOptions/Libs/LibStub/tests/ (stored 0%)
  adding: ItemRackOptions/Libs/LibStub/tests/test.lua (deflated 71%)
  adding: ItemRackOptions/Libs/LibStub/tests/test2.lua (deflated 58%)
  adding: ItemRackOptions/Libs/LibStub/tests/test3.lua (deflated 52%)
  adding: ItemRackOptions/Libs/LibStub/tests/test4.lua (deflated 66%)


Packaging complete.`

but when logging in on the tbc beta servers I get some lua errors I didn't get with the master version:
`Message: ...temRack\Libs\LibDataBroker-1.1\LibDataBroker-1.1.lua:3: LibDataBroker-1.1 requires CallbackHandler-1.0
Time: Mon May 17 19:17:35 2021
Count: 1
Stack: ...temRack\Libs\LibDataBroker-1.1\LibDataBroker-1.1.lua:3: LibDataBroker-1.1 requires CallbackHandler-1.0
[string "=[C]"]: in function `assert'
[string "@Interface\AddOns\ItemRack\Libs\LibDataBroker-1.1\LibDataBroker-1.1.lua"]:3: in main chunk

Locals: (*temporary) = nil
(*temporary) = "LibDataBroker-1.1 requires CallbackHandler-1.0"
`
`Message: ...AddOns\ItemRack\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:12: LibDBIcon-1.0 requires LibDataBroker-1.1.
Time: Mon May 17 19:17:35 2021
Count: 1
Stack: ...AddOns\ItemRack\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:12: LibDBIcon-1.0 requires LibDataBroker-1.1.
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\ItemRack\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua"]:12: in main chunk

Locals: (*temporary) = "LibDBIcon-1.0 requires LibDataBroker-1.1."
`
`Message: Interface\AddOns\ItemRack\ItemRack.lua:15: Cannot find a library instance of "LibDataBroker-1.1".
Time: Mon May 17 19:17:35 2021
Count: 1
Stack: Interface\AddOns\ItemRack\ItemRack.lua:15: Cannot find a library instance of "LibDataBroker-1.1".
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\ItemRack\Libs\LibStub\LibStub.lua"]:38: in function `LibStub'
[string "@Interface\AddOns\ItemRack\ItemRack.lua"]:15: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "LibDataBroker-1.1"."
`

Do you know what went wrong?

**Comment by mrbuds** [comment]
I forget to include CallbackHandler-1.0, it should be fixed now

**Review by Rottenbeer — APPROVED** [review]

**Comment by Rottenbeer** [comment]
@mrbuds People miss the square minimap functionality on curseforge, do you have an idea how to bring it back with the new library?

**Comment by mrbuds** [comment]
> 
> 
> @mrbuds People miss the square minimap functionality on curseforge, do you have an idea how to bring it back with the new library?

with a squared minimap (i use sexymap) it automatically anchor correctly
img

**Pull request merged**
