### PR TITLE
multi-toc support

### PR DESCRIPTION
**Pull request by jelmerj**
currently WoW classic era still shows the addon as being outdated. I believe multi-TOC is the answer to that, as specified https://wowpedia.fandom.com/wiki/TOC_format and https://support.overwolf.com/en/support/solutions/articles/9000209856-multi-toc-for-world-of-warcraft-addons
The current way of using Interface-BCC in the toc is legacy.
With these changes the addon shows as uptodate on both classic and wotlk

### CODE REVIEW

**Comment by Rottenbeer** [comment]
I use the bigwigsmod packager script to do the variant handling and create the correct .toc files.
The Interface- Variables are evaluated by the release.sh script and then put into the correct variant.

What' the current patch version for classic?

**Comment by Rottenbeer** [comment]
If you want to test the addon locally, just do `./release.sh -d -g wrath -n "{package-name}-{project-version}-wrath"` for the correct version and use the packages files to test in wow

**Comment by jelmerj** [comment]
Hmm, interesting. Looks like v2 of the packager should be used to support this: https://github.com/BigWigsMods/packager#building-for-multiple-game-versions
And indeed, I see it has the option enable-toc-creation to create the toc files automatically.

Looks like this pull request is not needed :)

Classic is currently at 11403, which is indeed ahead of what's specified in the TOC right now

**Comment by Rottenbeer** [comment]
Change ## Interface-Classic: 11400 to 11403, run the packager script with `./release.sh -d -g classic-n "{package-name}-{project-version}` and test the zip file and it should work for you

**Comment by Rottenbeer** [comment]
Solved by #210

**Pull request closed without merging**
