### PR TITLE
Cataclysm Classic Compatibility

### PR DESCRIPTION
**Pull request by Road-block**

### CODE REVIEW

**Comment by Road-block** [comment]
Package for testing https://github.com/Road-block/ItemRack/releases/latest

**Review by Rottenbeer — APPROVED** [review]

**Comment by Rottenbeer** [comment]
Thanks!

**Comment by Rottenbeer** [comment]
@Road-block I added a cata package, can you check if it works? I don't have a subscription anymore.

**Comment by Road-block** [comment]
image
Works on the current beta build at least.

**Pull request merged**
