### PR TITLE
Add per-set helm/cloak display options

### PR DESCRIPTION
**Pull request by btnmasher**
The frame XML could probably be a little better, I'm not that great with that stuff.

### CODE REVIEW

**Comment by btnmasher** [comment]
Having issue with the correct state of helm/cloak display when unequipping an event-driven set. Not sure exactly where I need to place the change state functions to make sure it gets caught, or if the fields in the `ItemUser.Set` table are being nil'd by being temporary.

**Comment by btnmasher** [comment]
I rewrote my initial version, having found the implementation to be very similar to the original ItemRack v2.98 implementation that I rediscovered during the process of bugfixing. I decided to instead carve out the original implementation from v2.98 with accompanying tri-state checkbox and weld it back into the classic version.

**Comment by Rottenbeer** [comment]
Thanks a lot for the pull request.
Can you do me a favor and show me some demo of it in action (screenshots, video...), I don't have a WoW account anymore.
I'll review the code afterwards ;)

**Comment by btnmasher** [comment]
https://cdn.discordapp.com/attachments/691772891854798902/727025203531612190/WowClassic_0QvDIEXJ9L.png

Ignore state leaves the display option as-is (on set switch, and is the defaulted option)

Show/Hide state do what would be expected of those options. The code is nearly 1:1 with the code in the mainline ItemRack version 2.98 prior to the release of Legion when the code was stripped out due to the change in how cloak/helm display worked. The only modification I made is that if the set that's being edited is the currently-equipped set, the changes in display will be reflected on the character immediately. (Also, the display state does not need to be saved with the save button, which is consistent with how this feature behaved from the original retail version).

**Comment by Rottenbeer** [comment]
Thanks for the PR

**Pull request merged**
